<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PermohonanSeeder extends Seeder
{
    /**
     * Jalankan seeder.
     */
    public function run(): void
    {
        // kosongkan tabel dulu biar tidak dobel data
        DB::table('permohonan')->truncate();

        DB::table('permohonan')->insert([
            [
                'id_instansi' => 1,
                'tgl_surat' => '2025-01-10',
                'instansi' => 'SMK Negeri 1 Pekanbaru',
                'tgl_mulai' => '2025-02-01',
                'tgl_selesai' => '2025-04-30',
                'pembimbing_sekolah' => 'Budi Santoso',
                'kontak_pembimbing' => '081234567890',
                'tgl_suratmasuk' => '2025-01-12',
                'jenis_magang' => 'Sekolah',
                'status' => 'Proses',
                'file_permohonan' => 'permohonan_smk1.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 2,
                'tgl_surat' => '2025-01-15',
                'instansi' => 'SMA Negeri 8 Pekanbaru',
                'tgl_mulai' => '2025-03-01',
                'tgl_selesai' => '2025-06-01',
                'pembimbing_sekolah' => 'Dewi Lestari',
                'kontak_pembimbing' => '089876543210',
                'tgl_suratmasuk' => '2025-01-16',
                'jenis_magang' => 'MBKM',
                'status' => 'Aktif',
                'file_permohonan' => 'permohonan_unri.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 3,
                'tgl_surat' => '2025-02-01',
                'instansi' => 'SMK Negeri 4 Pekanbaru',
                'tgl_mulai' => '2025-04-01',
                'tgl_selesai' => '2025-07-30',
                'pembimbing_sekolah' => 'Rahmat Hidayat',
                'kontak_pembimbing' => '082134567891',
                'tgl_suratmasuk' => '2025-02-05',
                'jenis_magang' => 'Mandiri',
                'status' => 'Selesai',
                'file_permohonan' => 'permohonan_telkom.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 4,
                'tgl_surat' => '2025-02-05',
                'instansi' => 'SMK Negeri 1 Bangkinang',
                'tgl_mulai' => '2025-03-01',
                'tgl_selesai' => '2025-05-30',
                'pembimbing_sekolah' => 'Siti Aminah',
                'kontak_pembimbing' => '081234567891',
                'tgl_suratmasuk' => '2025-02-06',
                'jenis_magang' => 'Sekolah',
                'status' => 'Ditolak',
                'file_permohonan' => 'permohonan_smk2.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 5,
                'tgl_surat' => '2025-02-10',
                'instansi' => 'SMK Negeri 3 Pekanbaru',
                'tgl_mulai' => '2025-03-15',
                'tgl_selesai' => '2025-06-15',
                'pembimbing_sekolah' => 'Andi Wijaya',
                'kontak_pembimbing' => '082345678912',
                'tgl_suratmasuk' => '2025-02-12',
                'jenis_magang' => 'MBKM',
                'status' => 'Aktif',
                'file_permohonan' => 'permohonan_pcr.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 6,
                'tgl_surat' => '2025-02-12',
                'instansi' => 'SMK Abdurrab Pekanbaru',
                'tgl_mulai' => '2025-04-01',
                'tgl_selesai' => '2025-08-01',
                'pembimbing_sekolah' => 'Yusuf Ramadhan',
                'kontak_pembimbing' => '081278945612',
                'tgl_suratmasuk' => '2025-02-14',
                'jenis_magang' => 'Mandiri',
                'status' => 'Proses',
                'file_permohonan' => 'permohonan_chevron.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 7,
                'tgl_surat' => '2025-02-14',
                'instansi' => 'SMK Kansai',
                'tgl_mulai' => '2025-03-10',
                'tgl_selesai' => '2025-06-10',
                'pembimbing_sekolah' => 'Sri Wahyuni',
                'kontak_pembimbing' => '081234512345',
                'tgl_suratmasuk' => '2025-02-15',
                'jenis_magang' => 'Sekolah',
                'status' => 'Aktif',
                'file_permohonan' => 'permohonan_smk3.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 8,
                'tgl_surat' => '2025-02-18',
                'instansi' => 'SMK Dar El Hikmah',
                'tgl_mulai' => '2025-04-01',
                'tgl_selesai' => '2025-07-01',
                'pembimbing_sekolah' => 'Fajar Nugraha',
                'kontak_pembimbing' => '089812345678',
                'tgl_suratmasuk' => '2025-02-19',
                'jenis_magang' => 'MBKM',
                'status' => 'Selesai',
                'file_permohonan' => 'permohonan_uir.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 9,
                'tgl_surat' => '2025-02-20',
                'instansi' => 'SMK Muhammadiyah Pekanbaru',
                'tgl_mulai' => '2025-04-15',
                'tgl_selesai' => '2025-07-15',
                'pembimbing_sekolah' => 'Nur Aisyah',
                'kontak_pembimbing' => '081223344556',
                'tgl_suratmasuk' => '2025-02-22',
                'jenis_magang' => 'Mandiri',
                'status' => 'Aktif',
                'file_permohonan' => 'permohonan_pln.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 10,
                'tgl_surat' => '2025-02-22',
                'instansi' => 'SMK Negeri 4 Pekanbaru',
                'tgl_mulai' => '2025-03-20',
                'tgl_selesai' => '2025-05-20',
                'pembimbing_sekolah' => 'Joko Purnomo',
                'kontak_pembimbing' => '082145678901',
                'tgl_suratmasuk' => '2025-02-24',
                'jenis_magang' => 'Sekolah',
                'status' => 'Ditolak',
                'file_permohonan' => 'permohonan_smk4.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 11,
                'tgl_surat' => '2025-02-25',
                'instansi' => 'SMK Telkom Pekanbaru',
                'tgl_mulai' => '2025-04-10',
                'tgl_selesai' => '2025-07-10',
                'pembimbing_sekolah' => 'Ahmad Fauzi',
                'kontak_pembimbing' => '081289765432',
                'tgl_suratmasuk' => '2025-02-26',
                'jenis_magang' => 'MBKM',
                'status' => 'Selesai',
                'file_permohonan' => 'permohonan_unilak.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 12,
                'tgl_surat' => '2025-02-27',
                'instansi' => 'PT Pertamina Hulu Rokan',
                'tgl_mulai' => '2025-04-20',
                'tgl_selesai' => '2025-08-20',
                'pembimbing_sekolah' => 'Rina Kartika',
                'kontak_pembimbing' => '081234567891',
                'tgl_suratmasuk' => '2025-02-28',
                'jenis_magang' => 'Mandiri',
                'status' => 'Aktif',
                'file_permohonan' => 'permohonan_pertamina.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 13,
                'tgl_surat' => '2025-03-01',
                'instansi' => 'SMK Negeri 5 Pekanbaru',
                'tgl_mulai' => '2025-04-15',
                'tgl_selesai' => '2025-07-15',
                'pembimbing_sekolah' => 'Yanti Marlina',
                'kontak_pembimbing' => '081256789012',
                'tgl_suratmasuk' => '2025-03-02',
                'jenis_magang' => 'Sekolah',
                'status' => 'Ditolak',
                'file_permohonan' => 'permohonan_smk5.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 14,
                'tgl_surat' => '2025-03-05',
                'instansi' => 'SMK Negeri 1 Pekanbaru',
                'tgl_mulai' => '2025-05-01',
                'tgl_selesai' => '2025-08-01',
                'pembimbing_sekolah' => 'Hendra Wijaya',
                'kontak_pembimbing' => '081234987654',
                'tgl_suratmasuk' => '2025-03-06',
                'jenis_magang' => 'MBKM',
                'status' => 'Aktif',
                'file_permohonan' => 'permohonan_umri.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_instansi' => 15,
                'tgl_surat' => '2025-03-10',
                'instansi' => 'SMK Negeri 5 Pekanbaru',
                'tgl_mulai' => '2025-05-15',
                'tgl_selesai' => '2025-08-15',
                'pembimbing_sekolah' => 'Indra Saputra',
                'kontak_pembimbing' => '081298765432',
                'tgl_suratmasuk' => '2025-03-12',
                'jenis_magang' => 'Mandiri',
                'status' => 'Ditolak',
                'file_permohonan' => 'permohonan_brks.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
